# Generated by Django 5.0.6 on 2025-09-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movement",
            name="last_stock",
            field=models.IntegerField(default=0),
        ),
    ]
