# Generated by Django 5.0.6 on 2025-09-15 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                choices=[
                    ("consommable", "Consommable"),
                    ("medicament", "Médicament"),
                    ("materiel", "Matériel"),
                    ("autre", "Autre"),
                ],
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stock.category",
            ),
        ),
    ]
