# Generated by Django 5.0.6 on 2025-09-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_movement_last_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="last_stock",
            field=models.IntegerField(default=0),
        ),
    ]
