# Generated by Django 5.0.6 on 2025-09-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_product_last_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movement",
            name="movement_type",
            field=models.CharField(
                choices=[("IN", "IN"), ("OUT", "OUT")], max_length=3
            ),
        ),
    ]
