# Generated by Django 5.0.6 on 2025-09-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_alter_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movement",
            old_name="quantity",
            new_name="curent_stock",
        ),
    ]
