# Generated by Django 5.0.6 on 2025-09-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_alter_movement_movement_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="current_stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="movement",
            name="movement_type",
            field=models.CharField(
                choices=[("IN", "Entrée"), ("OUT", "Sortie")], max_length=3
            ),
        ),
    ]
