# Generated by Django 5.0.6 on 2025-09-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_rename_quantity_movement_curent_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movement",
            old_name="curent_stock",
            new_name="quantity",
        ),
    ]
