# Generated by Django 5.0.6 on 2025-09-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_product_current_stock_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("consommable", "Consommable"),
                    ("medicament", "Médicament"),
                    ("materiel", "Matériel"),
                    ("autre", "Autre"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
