# Generated by Django 5.0.6 on 2025-09-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0006_alter_category_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movement",
            old_name="quantity",
            new_name="movement_quantity",
        ),
    ]
