# Generated by Django 5.0.6 on 2025-10-18 15:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom du cabinet"),
                ),
                (
                    "slogan",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Slogan / Sous-titre"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="clinic_logos/",
                        verbose_name="Logo du cabinet",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#0d6efd",
                        max_length=7,
                        verbose_name="Couleur principale",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#6c757d",
                        max_length=7,
                        verbose_name="Couleur secondaire",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#ffffff", max_length=7, verbose_name="Couleur de fond"
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        default="Arial, sans-serif",
                        max_length=100,
                        verbose_name="Police du site",
                    ),
                ),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
                ("linkedin", models.URLField(blank=True, verbose_name="LinkedIn")),
                (
                    "show_logo",
                    models.BooleanField(default=True, verbose_name="Afficher le logo"),
                ),
                (
                    "show_slogan",
                    models.BooleanField(
                        default=True, verbose_name="Afficher le slogan"
                    ),
                ),
                (
                    "dark_mode_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Activer le mode sombre"
                    ),
                ),
                (
                    "opening_hours",
                    models.TextField(blank=True, verbose_name="Horaires d'ouverture"),
                ),
            ],
            options={
                "verbose_name": "Information du cabinet",
                "verbose_name_plural": "Informations du cabinet",
            },
        ),
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("SUPPRESSION_PATIENT", "Suppression de patient"),
                            ("RESTAURATION_PATIENT", "Restauration de patient"),
                        ],
                        max_length=50,
                    ),
                ),
                ("patient_last_name", models.CharField(max_length=100)),
                ("patient_id", models.IntegerField(blank=True, null=True)),
                ("horodatage", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
