# Generated by Django 5.0.6 on 2025-10-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinicInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom du cabinet"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="clinic_logos/",
                        verbose_name="Logo du cabinet",
                    ),
                ),
                ("slogan", models.CharField(blank=True, max_length=255)),
                (
                    "primary_color",
                    models.CharField(
                        default="#0d6efd",
                        max_length=7,
                        verbose_name="Couleur principale",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#6c757d",
                        max_length=7,
                        verbose_name="Couleur secondaire",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#ffffff", max_length=7, verbose_name="Couleur de fond"
                    ),
                ),
            ],
            options={
                "verbose_name": "Information du cabinet",
                "verbose_name_plural": "Informations du cabinet",
            },
        ),
    ]
