# Generated by Django 5.0.6 on 2025-10-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicinfo",
            name="dark_mode_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Activer le mode sombre"
            ),
        ),
        migrations.AddField(
            model_name="clinicinfo",
            name="facebook",
            field=models.URLField(blank=True, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="clinicinfo",
            name="font_family",
            field=models.CharField(
                default="Arial, sans-serif",
                max_length=100,
                verbose_name="Police du site",
            ),
        ),
        migrations.AddField(
            model_name="clinicinfo",
            name="instagram",
            field=models.URLField(blank=True, verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="clinicinfo",
            name="linkedin",
            field=models.URLField(blank=True, verbose_name="LinkedIn"),
        ),
        migrations.AddField(
            model_name="clinicinfo",
            name="opening_hours",
            field=models.TextField(
                blank=True,
                help_text="Ex : Lundi-Vendredi 09h-18h",
                verbose_name="Horaires d'ouverture",
            ),
        ),
        migrations.AddField(
            model_name="clinicinfo",
            name="show_logo",
            field=models.BooleanField(
                default=True, verbose_name="Afficher le logo sur le site"
            ),
        ),
        migrations.AddField(
            model_name="clinicinfo",
            name="show_slogan",
            field=models.BooleanField(default=True, verbose_name="Afficher le slogan"),
        ),
        migrations.AlterField(
            model_name="clinicinfo",
            name="slogan",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Slogan / Sous-titre"
            ),
        ),
    ]
