# Generated by Django 5.0.6 on 2025-10-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="activation_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
