# Generated by Django 5.0.6 on 2025-10-01 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(blank=True, verbose_name="Texte de l’ordonnance"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créée le"),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="appointments.appointment",
                        verbose_name="Rendez-vous",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordonnance",
                "verbose_name_plural": "Ordonnances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medicament",
                    models.CharField(max_length=255, verbose_name="Nom du médicament"),
                ),
                (
                    "posologie",
                    models.CharField(max_length=255, verbose_name="Posologie"),
                ),
                ("quantite", models.PositiveIntegerField(verbose_name="Quantité")),
                (
                    "unite",
                    models.CharField(
                        help_text="Ex: boîte, flacon, injection, suppositoire…",
                        max_length=100,
                        verbose_name="Unité",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="prescriptions.prescription",
                        verbose_name="Ordonnance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Médicament prescrit",
                "verbose_name_plural": "Médicaments prescrits",
            },
        ),
    ]
