# Generated by Django 5.0.6 on 2025-09-25 14:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_alter_appointment_date_alter_appointment_done_and_more"),
        ("prescriptions", "0002_alter_prescription_appointment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prescription",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Ordonnance",
                "verbose_name_plural": "Ordonnances",
            },
        ),
        migrations.AddField(
            model_name="prescription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Créée le",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="prescription",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to="appointments.appointment",
                verbose_name="Rendez-vous",
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="text",
            field=models.TextField(verbose_name="Texte de l’ordonnance"),
        ),
    ]
