# Generated by Django 5.0.6 on 2025-09-26 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prescriptions",
            "0003_alter_prescription_options_prescription_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="text",
            field=models.TextField(blank=True, verbose_name="Texte de l’ordonnance"),
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medicament",
                    models.CharField(max_length=255, verbose_name="Nom du médicament"),
                ),
                (
                    "posologie",
                    models.CharField(max_length=255, verbose_name="Posologie"),
                ),
                ("quantite", models.PositiveIntegerField(verbose_name="Quantité")),
                (
                    "unite",
                    models.CharField(
                        help_text="Ex: boîte, flacon, injection, suppositoire…",
                        max_length=100,
                        verbose_name="Unité",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="prescriptions.prescription",
                        verbose_name="Ordonnance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Médicament prescrit",
                "verbose_name_plural": "Médicaments prescrits",
            },
        ),
    ]
