# Generated by Django 5.0.6 on 2025-10-01 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date du rendez-vous")),
                ("time", models.TimeField(verbose_name="Heure du rendez-vous")),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="Motif"),
                ),
                (
                    "done",
                    models.BooleanField(
                        default=False, verbose_name="Rendez-vous effectué"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Planifié"),
                            ("completed", "Terminé"),
                            ("canceled", "Annulé"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "medecin",
                    models.ForeignKey(
                        limit_choices_to={"role": "medecin"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments_medecin",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Médecin",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendez-vous",
                "verbose_name_plural": "Rendez-vous",
                "ordering": ["-date", "-time"],
            },
        ),
    ]
