# Generated by Django 5.0.6 on 2025-09-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={
                "ordering": ["-date", "-time"],
                "verbose_name": "Rendez-vous",
                "verbose_name_plural": "Rendez-vous",
            },
        ),
        migrations.RenameField(
            model_name="appointment",
            old_name="doctor",
            new_name="medecin",
        ),
    ]
