# Generated by Django 5.0.6 on 2025-10-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Planifié"),
                    ("present", "Présent"),
                    ("completed", "Terminé"),
                    ("canceled", "Annulé"),
                ],
                default="scheduled",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
