# Generated by Django 5.0.6 on 2025-09-25 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_alter_appointment_options_and_more"),
        ("patients", "0002_remove_appointment_patient_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(verbose_name="Date du rendez-vous"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="done",
            field=models.BooleanField(
                default=False, verbose_name="Rendez-vous effectué"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="medecin",
            field=models.ForeignKey(
                limit_choices_to={"role": "medecin"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments_medecin",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Médecin",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="patients.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="reason",
            field=models.TextField(blank=True, null=True, verbose_name="Motif"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Planifié"),
                    ("completed", "Terminé"),
                    ("canceled", "Annulé"),
                ],
                default="scheduled",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.TimeField(verbose_name="Heure du rendez-vous"),
        ),
    ]
