# Generated by Django 5.0.6 on 2025-10-18 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("phone", models.CharField(max_length=20, unique=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("medical_history", models.TextField(blank=True, null=True)),
                (
                    "consultation_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=500.0,
                        help_text="Tarif standard de consultation",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actif", models.BooleanField(default=True)),
                ("date_suppression", models.DateTimeField(blank=True, null=True)),
                (
                    "medecin",
                    models.ForeignKey(
                        limit_choices_to={"role": "medecin"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
