# Generated by Django 5.0.6 on 2025-09-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="billing",
            name="appointment",
        ),
        migrations.DeleteModel(
            name="Prescription",
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="Billing",
        ),
    ]
